#
# Custom opkg feed configuration for bt-r320
#

src/gz openwrt_core https://downloads.immortalwrt.org/releases/24.10.6/targets/mediatek/filogic/packages
src/gz openwrt_base https://downloads.immortalwrt.org/releases/24.10.6/targets/mediatek/filogic/packages
src/gz openwrt_luci https://downloads.immortalwrt.org/releases/24.10.6/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages https://downloads.immortalwrt.org/releases/24.10.6/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing https://downloads.immortalwrt.org/releases/24.10.6/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony https://downloads.immortalwrt.org/releases/24.10.6/packages/aarch64_cortex-a53/telephony
