#
# clean-up.yml — Clean up old workflow runs
#

name: Cleanup

on:
  workflow_call:
    inputs:
      clean-release:
        required: false
        type: boolean
        default: true

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete releases
        if: inputs.clean-release
        uses: dev-drprasad/delete-all-releases@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-error: true

      - name: Cleanup older runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 7
          keep_minimum_runs: 3
